<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#2.1.-Numpy-ndarray---создание" data-toc-modified-id="2.1.-Numpy-ndarray---создание-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>2.1. Numpy ndarray - создание</a></span></li><li><span><a href="#2.2.-Numpy-ndarray---индексы" data-toc-modified-id="2.2.-Numpy-ndarray---индексы-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>2.2. Numpy ndarray - индексы</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.3.-Numpy-ndarray---элементарные-операции-с-массивами" data-toc-modified-id="2.3.-Numpy-ndarray---элементарные-операции-с-массивами-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>2.3. Numpy ndarray - элементарные операции с массивами</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.4.-Numpy---основные-функции." data-toc-modified-id="2.4.-Numpy---основные-функции.-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>2.4. Numpy - основные функции.</a></span><ul class="toc-item"><li><span><a href="#TLDR:" data-toc-modified-id="TLDR:-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>TLDR:</a></span></li></ul></li><li><span><a href="#2.5.-Numpy---I/O." data-toc-modified-id="2.5.-Numpy---I/O.-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>2.5. Numpy - I/O.</a></span></li></ul></div>

In [19]:
%matplotlib inline
import matplotlib.pyplot as plt

# 2.1. Numpy ndarray - создание

Numpy - библиотека для векторизованных вычислений в Python'e. Написана на C. Основной объект в numpy - nddarray, который располагается напрерывно в памяти и позволяет производить быстрые вычисления.

In [20]:
import numpy as np

In [21]:
%%timeit
[[i**2 for i in list(range(100))]]

81.6 µs ± 9.74 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [22]:
%%timeit
a = np.array(list(range(100)))
a * a

33.9 µs ± 6.33 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [23]:
%%timeit
a = np.array(list(range(100)))
a ** 2

24.3 µs ± 4.75 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


Создание массива

In [24]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [25]:
a.shape

(4,)

Shape - кортеж, который указывает число элементов в каждом измерении. 

In [26]:
a = np.array([[1, 2], [3, 4]], dtype=int)

In [27]:
a.size

4

In [28]:
a.shape

(2, 2)

In [29]:
a.dtype

dtype('int32')

In [30]:
a.itemsize

4

In [31]:
a.nbytes

16

In [32]:
a.strides

(8, 4)

In [33]:
a.reshape(4, 1)

array([[1],
       [2],
       [3],
       [4]])

In [34]:
a.reshape(4, 1).strides

(4, 4)

In [35]:
a.reshape(1, 4).strides

(16, 4)

In [36]:
a.reshape(1, 3)

ValueError: cannot reshape array of size 4 into shape (1,3)

In [37]:
a.reshape(1, -1)

array([[1, 2, 3, 4]])

In [38]:
a.reshape(1, -1).shape

(1, 4)

При желании, можно использовать np.size(np.object) и np.shape(np.object):

In [39]:
np.size(a)

4

In [40]:
np.shape(a)

(2, 2)

При необходимости, не стоит принебрегать встроенной справкой:

In [41]:
np.array()

TypeError: array() missing required argument 'object' (pos 1)

И специальными функциями numpy:

In [42]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.lib.Arrayterator
    Buffered iterator for big arrays.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.ma.MaskedArray.__new__
    Create a 

и IPython:

In [43]:
np.con*?

np.concatenate
np.conj
np.conjugate
np.convolve

In [44]:
a

array([[1, 2],
       [3, 4]])

In [45]:
a[0, 0] = 100

In [46]:
a

array([[100,   2],
       [  3,   4]])

**Создание массивов**

Создавать из списков мы уже умеем:

In [47]:
np.array([1, 2, 3, 4], dtype=np.int16)

array([1, 2, 3, 4], dtype=int16)

In [48]:
np.arange(1, 10, 1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.linspace(0, 1, 25)

array([0.        , 0.04166667, 0.08333333, 0.125     , 0.16666667,
       0.20833333, 0.25      , 0.29166667, 0.33333333, 0.375     ,
       0.41666667, 0.45833333, 0.5       , 0.54166667, 0.58333333,
       0.625     , 0.66666667, 0.70833333, 0.75      , 0.79166667,
       0.83333333, 0.875     , 0.91666667, 0.95833333, 1.        ])

In [50]:
np.linspace(0, 1, 25, endpoint=False)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96])

In [51]:
np.linspace(0, 1, 26)

array([0.  , 0.04, 0.08, 0.12, 0.16, 0.2 , 0.24, 0.28, 0.32, 0.36, 0.4 ,
       0.44, 0.48, 0.52, 0.56, 0.6 , 0.64, 0.68, 0.72, 0.76, 0.8 , 0.84,
       0.88, 0.92, 0.96, 1.  ])

In [52]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
np.ones(3)

array([1., 1., 1.])

In [54]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
np.diag(np.array([1, 2, 3, 4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

** Случайные массивы **

на интервале [0,1]:

In [57]:
np.random.rand(3, 2)

array([[0.83476388, 0.46040098],
       [0.34857537, 0.48340468],
       [0.82798856, 0.25304251]])

Нормально распределенные:

In [58]:
np.random.randn(3, 2)

array([[ 0.79168606,  1.6638948 ],
       [-0.41811545, -0.33609339],
       [-0.13089176,  0.76759044]])

-- N: иногда полезно получить случайное целое число:

In [59]:
np.random.randint(2, 10)

8

# 2.2. Numpy ndarray - индексы

Отдельно рассмотрим 1-мерный и многомерные массивы.

In [60]:
t = np.random.rand(3)

In [61]:
t

array([0.14803893, 0.21182114, 0.00998224])

Для одномерного массива получим сразу элемент, который находится по данному индексу. Для n-мерного массива подобная индексация вернет массив размера n-1.

In [62]:
t = np.random.rand(3, 5, 10)
t

array([[[0.34225675, 0.50754772, 0.14360024, 0.65930865, 0.81379481,
         0.06724755, 0.54701598, 0.08536135, 0.71825368, 0.65028936],
        [0.67591155, 0.29075188, 0.23081349, 0.6757261 , 0.82710064,
         0.62365138, 0.26011891, 0.293965  , 0.74522878, 0.44790771],
        [0.61566417, 0.50010881, 0.08215644, 0.51485306, 0.85470245,
         0.51231456, 0.49445796, 0.52263995, 0.84503946, 0.66407027],
        [0.03998907, 0.96840943, 0.45518539, 0.52424663, 0.96401022,
         0.80921925, 0.00490464, 0.3880234 , 0.25081308, 0.55539271],
        [0.76957291, 0.15863932, 0.77963357, 0.78711138, 0.25234065,
         0.42092166, 0.3677113 , 0.97062889, 0.36304473, 0.23663233]],

       [[0.06576307, 0.29072483, 0.88307193, 0.29978186, 0.14729405,
         0.29514488, 0.93365967, 0.56918439, 0.56512905, 0.84242321],
        [0.62884588, 0.34970589, 0.84424925, 0.72441148, 0.10101231,
         0.48096181, 0.20361124, 0.19686074, 0.85731826, 0.67357293],
        [0.41631346, 0.87

In [63]:
t.shape

(3, 5, 10)

In [64]:
t[0, 1, :]

array([0.67591155, 0.29075188, 0.23081349, 0.6757261 , 0.82710064,
       0.62365138, 0.26011891, 0.293965  , 0.74522878, 0.44790771])

In [65]:
t[1]

array([[0.06576307, 0.29072483, 0.88307193, 0.29978186, 0.14729405,
        0.29514488, 0.93365967, 0.56918439, 0.56512905, 0.84242321],
       [0.62884588, 0.34970589, 0.84424925, 0.72441148, 0.10101231,
        0.48096181, 0.20361124, 0.19686074, 0.85731826, 0.67357293],
       [0.41631346, 0.87532856, 0.06772698, 0.33479767, 0.57137511,
        0.60224088, 0.39464382, 0.6382749 , 0.01437136, 0.35503999],
       [0.41638003, 0.96658959, 0.06464366, 0.08765821, 0.8451607 ,
        0.80782158, 0.85563299, 0.88591644, 0.82973639, 0.93745423],
       [0.455365  , 0.8436072 , 0.44025202, 0.09023671, 0.09059528,
        0.34900364, 0.27636507, 0.02897881, 0.35292494, 0.23795288]])

In [66]:
np.random.rand(3, 5)[1].shape

(5,)

Можно использовать ':' вместо индекса:

In [67]:
A = np.random.rand(3, 5)

In [68]:
A

array([[4.51161663e-01, 1.13258245e-01, 5.05977065e-01, 1.08870336e-01,
        6.48448748e-01],
       [8.64974938e-01, 5.79060576e-01, 7.62923883e-01, 4.10940555e-01,
        6.78758254e-04],
       [2.98659955e-01, 2.38616431e-01, 4.26755614e-01, 6.51787917e-01,
        4.75712916e-01]])

In [69]:
A[0, :]

array([0.45116166, 0.11325824, 0.50597706, 0.10887034, 0.64844875])

In [70]:
A[:, 0]

array([0.45116166, 0.86497494, 0.29865995])

Поддерживается стандартный протокол - python slicing syntax ([lower:upper:step]) :

In [71]:
A[0, :]

array([0.45116166, 0.11325824, 0.50597706, 0.10887034, 0.64844875])

In [72]:
A[0, :][0:4:2]

array([0.45116166, 0.50597706])

In [73]:
a = A[0, :]

In [74]:
a

array([0.45116166, 0.11325824, 0.50597706, 0.10887034, 0.64844875])

Операция slicing создает т.н. view - то есть данные не копируются, поэтому исходный объект по адресу - mutable.

In [75]:
A[0,:][0:4:2]

array([0.45116166, 0.50597706])

In [76]:
A[0,:][0:4:2] = [1.0, 2.5]

In [77]:
A

array([[1.00000000e+00, 1.13258245e-01, 2.50000000e+00, 1.08870336e-01,
        6.48448748e-01],
       [8.64974938e-01, 5.79060576e-01, 7.62923883e-01, 4.10940555e-01,
        6.78758254e-04],
       [2.98659955e-01, 2.38616431e-01, 4.26755614e-01, 6.51787917e-01,
        4.75712916e-01]])

Параметры для slicing могут пропускаться:

In [78]:
A[0,:][0:4:2]

array([1. , 2.5])

In [79]:
A[0,:][0:4]

array([1.        , 0.11325824, 2.5       , 0.10887034])

In [80]:
A[0,:][:3]

array([1.        , 0.11325824, 2.5       ])

In [81]:
A[0,:][3:]

array([0.10887034, 0.64844875])

In [82]:
A[0,:]

array([1.        , 0.11325824, 2.5       , 0.10887034, 0.64844875])

In [83]:
A[0,:][::-1]

array([0.64844875, 0.10887034, 2.5       , 0.11325824, 1.        ])

In [84]:
A[0,:]

array([1.        , 0.11325824, 2.5       , 0.10887034, 0.64844875])

In [85]:
A[0,:][:-3]

array([1.        , 0.11325824])

In [86]:
A[0,:][-3:]

array([2.5       , 0.10887034, 0.64844875])

** Fancy Indexing **

Этим термином обозначается индексирование с помощью массивов (или иных итерируемых конструкций).

In [87]:
A

array([[1.00000000e+00, 1.13258245e-01, 2.50000000e+00, 1.08870336e-01,
        6.48448748e-01],
       [8.64974938e-01, 5.79060576e-01, 7.62923883e-01, 4.10940555e-01,
        6.78758254e-04],
       [2.98659955e-01, 2.38616431e-01, 4.26755614e-01, 6.51787917e-01,
        4.75712916e-01]])

In [88]:
row_indices = [1, 2]
A[row_indices]

array([[8.64974938e-01, 5.79060576e-01, 7.62923883e-01, 4.10940555e-01,
        6.78758254e-04],
       [2.98659955e-01, 2.38616431e-01, 4.26755614e-01, 6.51787917e-01,
        4.75712916e-01]])

In [89]:
col_indices = [1, -1]
A[row_indices, col_indices]

array([0.57906058, 0.47571292])

Возможно Булево индексирование (**Boolean indexing**):

In [90]:
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

In [91]:
B[B > 2]

array([3, 4])

In [92]:
row_mask = np.array([1, 0, 1, 0, 0], dtype=bool)
B[row_mask]

array([0, 2])

Это очень удобно, как вы наверняка догадались, если мы хотим отобрать данные, отвечающие определенным условиям:

In [93]:
x = np.arange(0, 10, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [94]:
mask = (5 < x) * (x < 7.5)
mask

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False])

In [95]:
x[mask]

array([5.5, 6. , 6.5, 7. ])

In [96]:
a = np.array([[1, 2], [3, 4]])

In [97]:
a * (a > 1)

array([[0, 2],
       [3, 4]])

In [98]:
a[a > 0]

array([1, 2, 3, 4])

Получить список индексов элементов, отвечающих заданной маске, можно с помощью **which**:

In [99]:
indices = np.where?

Docstring:
where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
nonzero : The function that is called when x and y are omitted

Notes
-----
If all the arrays are 1-D, `where` is equivalent to::

    [xv if c else yv
     for c, xv, yv in zip(condition, x, y)]

Examples
-

In [ ]:
indices = np.where

In [100]:
x[indices]

NameError: name 'indices' is not defined

**take** еще одна конструкция выбора элементов массива:

In [101]:
v = np.arange(-3, 3)
row_indices = [1, 3, 5]

In [102]:
v

array([-3, -2, -1,  0,  1,  2])

In [103]:
v[row_indices]

array([-2,  0,  2])

In [104]:
v.take(row_indices)

array([-2,  0,  2])

In [105]:
np.take(v, row_indices)

array([-2,  0,  2])

** choices ** - полезная функция для выбора элеметов из нескольких массивов:

In [106]:
which = [1, 0, 1, 0]
choices = [[-1, -2, -3, -4], [1, 2, 3, 4]]
np.choose(which, choices)

array([ 1, -2,  3, -4])

** compress ** - альтернативой Булевому индексированию:

In [107]:
a = np.array([[1, 2], [3, 4], [5, 6]])
np.compress([False, True, True], a, axis=0)

array([[3, 4],
       [5, 6]])

## TLDR:
* для доступа к элементам массива пользуйтесь slicing и помните, что slicing создает view, а значит исходный массив может быть изменен.

# 2.3. Numpy ndarray - элементарные операции с массивами

** Broadcasting **

Концепеция broadcasting является ключевой для понимания операций с массивами. Обычно, операции с массивами производятся поэлементно. 

In [108]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])

In [109]:
a / b

array([0.5, 1. , 1.5])

Что, если массивы разного размера? Начнем с простого - скаляр и вектор:

In [110]:
a = np.array([1.0, 2.0, 3.0])
b = 2.0
a * b

array([2., 4., 6.])

Все просто - скаляр словно "вырастает" (broadcasted) до размеров вектора и производится поэлементная операция (разумеется, это умозрительная аналогия - новый вектор из 2 не создается!).

Общее правило таково:

операция может произведена если размерность "крайних" осей массивов совпадает (trailing dimension), либо один из элементов является скаляром.

Пример из оффициальной документации:

In [111]:
'''

Image  (3d array): 256 x 256 x 3
Scale  (1d array):             3
Result (3d array): 256 x 256 x 3

A      (4d array):  8 x 1 x 6 x 1
B      (3d array):      7 x 1 x 5
Result (4d array):  8 x 7 x 6 x 5

'''
pass

а вот эти операции дадут вам ошибку:

In [112]:
'''
A      (1d array):  3
B      (1d array):  4 # trailing dimensions do not match

A      (2d array):      2 x 1
B      (3d array):  8 x 4 x 3 # second from last dimensions mismatched
'''
pass

In [113]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

print(x.shape)

print(y.shape)

x + y

(4,)
(5,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [114]:
print(xx.shape)
print(y.shape)
print((xx + y).shape)
print(xx + y)

print('-------')

print(x.shape)
print(z.shape)
print((x + z).shape)
print(x + z)

(4, 1)
(5,)
(4, 5)
[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]
-------
(4,)
(3, 4)
(3, 4)
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]


Классный пример из официальной документации:

In [115]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [116]:
a[:, np.newaxis]

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [117]:
a[:, np.newaxis].shape

(4, 1)

** Операции вида "массив - скаляр" **

In [118]:
A

array([[1.00000000e+00, 1.13258245e-01, 2.50000000e+00, 1.08870336e-01,
        6.48448748e-01],
       [8.64974938e-01, 5.79060576e-01, 7.62923883e-01, 4.10940555e-01,
        6.78758254e-04],
       [2.98659955e-01, 2.38616431e-01, 4.26755614e-01, 6.51787917e-01,
        4.75712916e-01]])

In [119]:
A + 2

array([[3.        , 2.11325824, 4.5       , 2.10887034, 2.64844875],
       [2.86497494, 2.57906058, 2.76292388, 2.41094056, 2.00067876],
       [2.29865995, 2.23861643, 2.42675561, 2.65178792, 2.47571292]])

** Операции вида "массив - массив" **

Производятся поэлементно с учетом правил broadcasting:

In [120]:
A * A

array([[1.00000000e+00, 1.28274300e-02, 6.25000000e+00, 1.18527501e-02,
        4.20485779e-01],
       [7.48181644e-01, 3.35311150e-01, 5.82052852e-01, 1.68872140e-01,
        4.60712767e-07],
       [8.91977685e-02, 5.69378012e-02, 1.82120354e-01, 4.24827489e-01,
        2.26302778e-01]])

In [121]:
A / A

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

** Матричные операции**

In [122]:
A = np.random.rand(3,3)

In [123]:
np.dot(A, A)

array([[1.38161724, 0.80271759, 0.58495794],
       [0.85337928, 0.48605948, 0.33130046],
       [0.5986781 , 0.39069456, 0.33590029]])

In [124]:
v = np.random.randn(3)

In [125]:
v

array([ 0.52400924,  0.43646895, -0.69035651])

In [126]:
v[:, np.newaxis]

array([[ 0.52400924],
       [ 0.43646895],
       [-0.69035651]])

In [127]:
A * v

array([[ 0.49354204,  0.24686735, -0.26410282],
       [ 0.37495887,  0.09743973, -0.05788057],
       [ 0.12300488,  0.1639884 , -0.31980596]])

In [128]:
np.dot(A, v)

array([ 0.47630656,  0.41451804, -0.03281268])

In [129]:
np.dot(A, v[:, np.newaxis])

array([[ 0.47630656],
       [ 0.41451804],
       [-0.03281268]])

In [130]:
np.dot(v[np.newaxis, :], A)

array([[ 0.64380787,  0.13444193, -0.08274672]])

In [131]:
np.dot(v, v)

0.941682943101174

Если хочется использовать по умолчанию операции из матричной алгебры, то можно использовать конструктор matrix().

In [132]:
M = np.matrix(A)

In [133]:
v1 = np.matrix(v).T

In [134]:
M.shape

(3, 3)

In [135]:
v1.shape

(3, 1)

In [136]:
v1.T * v1

matrix([[0.94168294]])

In [137]:
M * v1

matrix([[ 0.47630656],
        [ 0.41451804],
        [-0.03281268]])

** Преобразование массивов**

In [138]:
A.T

array([[0.9418575 , 0.71555775, 0.234738  ],
       [0.56560118, 0.2232455 , 0.37571607],
       [0.38256005, 0.08384156, 0.46324754]])

** reshape **

In [139]:
a

array([ 0., 10., 20., 30.])

In [140]:
a = a.reshape((2, 2))

In [141]:
a.reshape(2, -1)

array([[ 0., 10.],
       [20., 30.]])

** resize **

In [142]:
a = np.arange(4)

In [143]:
a.resize((8,))

In [144]:
a

array([0, 1, 2, 3, 0, 0, 0, 0])

** repeat **

In [145]:
a = np.array([[1, 2], [3, 4]])
np.repeat(a, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4])

In [146]:
np.tile(a, 3)

array([[1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4]])

** concatenate **

In [147]:
a

array([[1, 2],
       [3, 4]])

In [148]:
b = np.array([[5, 6]])

In [149]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [150]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

** hstack **

Название говорит само за себя - horizontal stack.

In [151]:
np.hstack((a, b.T))

array([[1, 2, 5],
       [3, 4, 6]])

In [152]:
a.shape

(2, 2)

In [153]:
b.T.shape

(2, 1)

** vstack **

In [154]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [155]:
a.shape

(2, 2)

In [156]:
b.shape

(1, 2)

** Копии и view **

Мы помним, что очень важно различать копирование объекта и присваивание новой ссылки на объект. Numpy в этом смысле не отличается от списков:

In [157]:
A = np.array([[1, 2], [3, 4]])

In [158]:
B = A

In [159]:
B[0, 0] = 10

In [160]:
A

array([[10,  2],
       [ 3,  4]])

Если это не тот тип поведения, который нам нужен - следует использовать np.copy():

In [161]:
A = np.array([[1, 2], [3, 4]])

In [162]:
B = np.copy(A)

In [163]:
B[0, 0] = 100

In [164]:
A

array([[1, 2],
       [3, 4]])

Важно помнить, что если вы используете view массива, то копии вы не создаете!

In [165]:
a = np.arange(10)

In [166]:
b = a[::2]

In [167]:
np.may_share_memory(a, b)

True

In [168]:
c = a[::2].copy()
np.may_share_memory(a, c)

False

In [169]:
d = a.T
np.may_share_memory(a, d)

True

## TLDR:
* следует отличать копию массива и view;
* при осуществлении операций помните про правила broadcasting;
* запомните hstack и vstack.

# 2.4. Numpy - основные функции.

** Встроенные функции массива **

In [170]:
m = np.random.rand(3,3)

In [171]:
m.sum()

4.60586908813564

In [172]:
m.max()

0.8517957899659669

** Всегда используйте встроенные функции! **

In [173]:
a = np.random.rand(100000)

In [174]:
%timeit -n 1000 max(a)

28 ms ± 4.75 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [175]:
%timeit -n 1000 a.max()

94.5 µs ± 15.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [176]:
%timeit -n 1000 sum(a)

65.4 ms ± 3.27 ms per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [177]:
%timeit -n 1000 a.sum()

151 µs ± 29.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Просто считать сумму элементов матрицы или находить максимальный элемент не так интересно, и тут нам помогают axis:

In [178]:
m

array([[0.74296407, 0.2077268 , 0.59154996],
       [0.85179579, 0.76068845, 0.49158992],
       [0.50949231, 0.2835398 , 0.16652198]])

In [179]:
m.sum(axis=0)

array([2.10425217, 1.25195506, 1.24966186])

In [180]:
m.sum(axis=1)

array([1.54224084, 2.10407416, 0.95955409])

In [181]:
m.max(axis=0)

array([0.85179579, 0.76068845, 0.59154996])

Очень полезно произведение всех элементов:

In [182]:
m.prod(axis=1)

array([0.09129601, 0.31852629, 0.02405599])

Кумулятивная сумма элементов:

In [183]:
a.cumsum() * 100

array([5.72193971e+01, 1.40988387e+02, 2.02464262e+02, ...,
       5.00428672e+06, 5.00435184e+06, 5.00438312e+06])

Кумулятивное произведение:

In [184]:
a.cumprod()

array([0.57219397, 0.47932111, 0.29466685, ..., 0.        , 0.        ,
       0.        ])

**Простые статистики**

**Среднее**

In [185]:
m.mean(axis=0)

array([0.70141739, 0.41731835, 0.41655395])

In [186]:
np.mean(m, axis=0)

array([0.70141739, 0.41731835, 0.41655395])

In [187]:
np.mean(a)

0.5004383116333089

In [188]:
a.mean()

0.5004383116333089

**Медиана**

In [189]:
np.median(m, axis=0)

array([0.74296407, 0.2835398 , 0.49158992])

In [190]:
np.median(a)

0.5007499162110227

** Дисперсия **

In [191]:
np.std(m, axis=0)

array([0.14279943, 0.24476407, 0.18144787])

In [192]:
m.std(axis=0)

array([0.14279943, 0.24476407, 0.18144787])

In [193]:
np.var(a)

0.08316513434822292

In [194]:
a.var()

0.08316513434822292

** Сортировка **

In [195]:
np.sort(a)

array([2.73190222e-05, 5.45720452e-05, 6.05524704e-05, ...,
       9.99987559e-01, 9.99993626e-01, 9.99996027e-01])

Функция выше возвращает отсортированную копию массива. Если нужна сортировка in-place:

In [196]:
a.sort()

In [197]:
a = np.random.rand(100000)

Также иногда бывает полезно получить только список индексов в правильном порядке:

In [198]:
np.argsort(a)

array([93972, 89071, 10091, ...,  9993, 29640, 91152], dtype=int64)

In [199]:
np.argmax(a)

91152

In [200]:
np.argmin(a)

93972

In [201]:
np.nonzero(a)

(array([    0,     1,     2, ..., 99997, 99998, 99999], dtype=int64),)

** Функции для работы с матрицами **

In [202]:
m

array([[0.74296407, 0.2077268 , 0.59154996],
       [0.85179579, 0.76068845, 0.49158992],
       [0.50949231, 0.2835398 , 0.16652198]])

In [203]:
np.diag(m)

array([0.74296407, 0.76068845, 0.16652198])

In [204]:
m.diagonal()

array([0.74296407, 0.76068845, 0.16652198])

Для целого класса функций из линейной алгебры есть свой суб-модуль np.linalg.

http://docs.scipy.org/doc/numpy/reference/routines.linalg.html

In [205]:
MM = np.random.randn(9, 6)

In [206]:
U, s, V = np.linalg.svd(MM, full_matrices=False)
U.shape, V.shape, s.shape

((9, 6), (6, 6), (6,))

In [207]:
S = np.diag(s)
np.allclose(MM, np.dot(U, np.dot(S, V)))

True

** Векторизация кода **

В numpy есть встроенная функция vectorize, которая "автоматически" векторизует вашу функцию:

In [208]:
def heavyside(x):
    if x >= 0:
        return 1
    else:
        return 0

In [209]:
heavyside(np.array([-3, -2, -1, 0, 1, 2, 3]))

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
heavyside_vec = np.vectorize(heavyside)

In [ ]:
heavyside_vec(np.array([-3, -2, -1, 0, 1, 2, 3]))

Тем не менее, лучше сразу пишите так:

In [ ]:
def heavyside(x):
    return 1 * (x >= 0)

In [ ]:
heavyside(np.array([-3,-2,-1,0,1,2,3]))

In [ ]:
np.array([-3,-2,-1,0,1,2,3]) >= 0

In [ ]:
1 * (np.array([-3,-2,-1,0,1,2,3]) >= 0)

** Условные выражения **

Как вы уже поняли, для вектора конструкция типа if (vector) не подходит.

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

## TLDR:
- всегда используйте встроенные в np функции;
- векторизуйте везде, где это возможно!

# 2.5. Numpy - I/O.

В данном случае у нас на выбор 2 опции - либо формат numpy, либо просто текстовый файл.

In [ ]:
np.save("random.npy", M)

In [ ]:
!ls

In [ ]:
np.load("random.npy")

In [ ]:
np.savetxt('random.csv', M, delimiter='\t')

In [ ]:
! cat random.csv

In [ ]:
np.loadtxt('random.csv')